CREATE TABLE Quote (
    id SERIAL PRIMARY KEY,
    author_id INTEGER NOT NULL,
    quote_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (author_id) REFERENCES Author (id) ON DELETE CASCADE
);